### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by sylvaincaillot** [sgjsakura/AspNetCore#16]
Good morning

I have been trying your plugin (latest version) for paging my search results but I am getting the following issue:
```
{System.Data.SqlClient.SqlException: Incorrect syntax near 'OFFSET'.
Invalid usage of the option NEXT in the FETCH statement.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
  ....
```

This is my code, everything worked well when I was using an IList:

```
            var pageNumber = 1; 
            var pageSize = 10;

            IQueryable<SearchResultViewModel> SearchVM = from item in _context.MyModel select new SearchResultViewModel()
                                                              {
                                                                A = item.a,
                                                                B= item.b
                                                            };


            model.SearchResults = SearchVM.ToPagedList(pageSize, pageNumber);
return model;
```

Thanks in advance for your input

S.

**Comment by sgjsakura** [comment]
@sylvaincaillot Hi, thank you for your feed back, this problem may caused by the EntityFramework Core library but not by the pager. Please try to remove the ToPagedList invokation and replace it with Skip and Take, e.g.
```C#
var result = (from i in myModel).Skip(10).Take(10);
```

If the problem still occurs, it then can be confirmed this problem is caused by EntityFramework. Please report this issue to the ASP.NET Core development team thought https://github.com/aspnet/EntityFramework/issues .While if the problem does not occur again, please let me know as soon as possible.

Thank you again and waiting for your kind reply :-)

**Comment by sylvaincaillot** [comment]
Thnak you @sgjsakura for your quick reply

I followed your advices and got the same error for the following:

```
IQueryable<SearchResultViewModel> SearchVM = (from item in _context.MyModel
                                                         select new SearchResultViewModel()
                                                         {
                                                             A = item.a,
                                                                B= item.b
                                                         }).Skip(10).Take(10);

            model.SearchResults = SearchVM.ToList();
            return model;
```
If I remove the .Skip(10).Take(10), it works fine...

So, I will check with EF core team to see what is going on. I will keep you informed.
Thank you anyway for your plugin, it looks very nice

Cheers

S.
